# Generated by Django 2.0.6 on 2018-10-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='connected_mentees',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
