# Generated by Django 2.0.6 on 2018-10-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoring',
            name='message',
            field=models.CharField(default='This is a message', max_length=3000),
        ),
    ]
