# Generated by Django 2.0.6 on 2018-10-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0002_mentee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='number',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
